steps:
  - name: 'docker'
    args: ['build', '-t', 'venkatrobin/food-app:v1', '.']

  - name: 'docker'
    args: ['push', 'venkatrobin/food-app:v1']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'food-site-service'
      - '--image=venkatrobin/food-app:v1'
      - '--platform=managed'
      - '--region=us-central1'
      - '--port=5000'
      - '--allow-unauthenticated'
      - '--set-env-vars=DOCKER_USERNAME=venkatrobin,DOCKER_PASSWORD=$(DOCKER_PASSWORD)'

availableSecrets:
  secretManager:
    - versionName: projects/peaceful-choir-427805/secrets/docker-hub-pwd/versions/latest
      env: 'DOCKER_PASSWORD'

options:
  logging: CLOUD_LOGGING_ONLY
