steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/$REPO_NAME:$COMMIT_SHA'
      - '.'
    env:
      - 'MYSQL_HOST=$_MYSQL_HOST'
      - 'MYSQL_USER=$_MYSQL_USER'
      - 'MYSQL_PASSWORD=$_MYSQL_PASSWORD'
      - 'MYSQL_DB=$_MYSQL_DB'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - $_CLOUD_RUN_SERVICE
      - --image
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO/$REPO_NAME:$COMMIT_SHA'
      - --region
      - $_REGION
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      - 'MYSQL_HOST=$_MYSQL_HOST,MYSQL_USER=$_MYSQL_USER,MYSQL_PASSWORD=$_MYSQL_PASSWORD,MYSQL_DB=$_MYSQL_DB'

substitutions:
  _MYSQL_HOST: ''
  _MYSQL_USER: ''
  _MYSQL_PASSWORD: ''
  _MYSQL_DB: ''
  _CLOUD_RUN_SERVICE: ''
  _REGION: ''
  _ARTIFACT_REPO: ''


options:
  logging: CLOUD_LOGGING_ONLY