steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'REGION-docker.pkg.dev/$PROJECT_ID/ARTIFACT_REPO/$REPO_NAME:$COMMIT_SHA'
      - '.'
    env:
      - 'MYSQL_HOST=${_MYSQL_HOST}'
      - 'MYSQL_USER=${_MYSQL_USER}'
      - 'MYSQL_PASSWORD=${_MYSQL_PASSWORD}'
      - 'MYSQL_DB=${_MYSQL_DB}'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - $CLOUD_RUN_SERVICE
      - --image
      - 'REGION-docker.pkg.dev/$PROJECT_ID/ARTIFACT_REPO/$REPO_NAME:$COMMIT_SHA'
      - --region
      - $REGION
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      - 'MYSQL_HOST=${_MYSQL_HOST},MYSQL_USER=${_MYSQL_USER},MYSQL_PASSWORD=${_MYSQL_PASSWORD},MYSQL_DB=${_MYSQL_DB}'

images:
  - 'REGION-docker.pkg.dev/$PROJECT_ID/ARTIFACT_REPO/$REPO_NAME:$COMMIT_SHA'